#meta property="og:title" content="Global Fitness & Wellness Service"
#meta property="og:description" content="Spot offers different fitness programs for individuals or groups."
#meta property="og:image" content="https://res.cloudinary.com/dhj0qswpc/image/upload/v1615307262/anastase-maragos-9dzwzqwzmde-u_1_llixdm.jpg"
#meta property="og:url" content="https://www.spot-476.com/"

meta_product_name: "SPOT"
meta_title: "SPOT - Global Fitness & Wellness Service"
meta_description: "Spot offers different fitness programs for individuals or groups."
meta_image: "meta.jpg"